config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, :only => :show, shallow: true do
    resources :goals, shallow: true do
      resources :milestones
      resources :posts, shallow: true do
        resources :comments
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :goal, inverse_of: :milestones

  enum status: [ :open, :closed, :completed ] #DO NOT change this order

  validates :status, :title, :description, :reach_by_date, :goal, presence: true
  validates :title, length: { maximum: 80 }
  validates :description, length: { maximum: 800 } #should only be for FREE users

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  load_and_authorize_resource :goal
  load_and_authorize_resource :milestone, :through => :goal, :shallow => true
  before_filter :set_goal

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @milestones = @milestones.order(reach_by_date: :desc).page(params[:page]).per(10)
  end

  def new
  end

  def create
    if @milestone.save
      redirect_to goal_milestones_path(@goal), notice: 'This milestone was successfully saved.'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @milestone.update_attributes(milestone_params)
      redirect_to milestone_path(@milestone), notice: 'This milestone was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @milestone.destroy
    redirect_to goal_milestones_path(@goal), notice: 'This milestone was deleted.'
  end

  def milestone_params
    params.require(:milestone).permit(:title, :description, :status, :reach_by_date, :goal_id)
  end

  protected

  def set_goal
    @goal ||= @milestone.goal
  end

end

app/views/milestones/_form.html.erb
<%= bootstrap_form_for @milestone.new_record? ? [@goal, @milestone] : [@milestone] do |f| %>

    <%= f.alert_message 'Please fix the errors below.' %>

    <% unless @milestone.new_record? %>
        <div class="field">
          <%= f.form_group :status, label: { text: 'Status' } do %>
              <%= f.radio_button :status, 'open', checked: @milestone.open?, label: 'Open' %>
              <%= f.radio_button :status, 'closed', checked: @milestone.closed?, label: 'Closed' %>
              <%= f.radio_button :status, 'completed', checked: @milestone.completed?, label: 'Completed' %>
          <% end %>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.text_field :reach_by_date, class: 'reach-by-date' %>
    </div>

    <div class="actions">
      <%= f.submit 'Save' %>
    </div>

<% end %>

app/views/milestones/_milestone.html.erb
<p>
  <strong>Status:</strong>
  <%= milestone.status.capitalize %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= display_full_date(milestone.reach_by_date) %>
</p>

<p>
  <strong>Title:</strong>
  <%= milestone.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= milestone.description %>
</p>

<% if can? :update, milestone %>
    <%= link_to 'Edit', edit_milestone_path(milestone) %>
<% end %>

<% if can? :destroy, milestone %>
    <%= link_to 'Delete', milestone_path(milestone), method: :delete, data: { confirm: 'Are you sure you want to delete this milestone?' } %>
<% end %>

app/views/milestones/edit.html.erb
<h1>Edit Milestone</h1>

<%= render 'form' %>

app/views/milestones/index.html.erb
<h1>Action Plan</h1>
<% if can? :create, Milestone.new(goal: @goal) %>
    <%= link_to 'Add Milestone', new_goal_milestone_path(@goal) %>
<% end %>

<% if @milestones.blank? %>
    <h4>You do not currently have any milestones</h4>
<% else %>
    <%= render @milestones %>
<% end %>

<%= paginate @milestones %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form' %>

app/views/milestones/show.html.erb
<%= render @milestone %>