config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, :only => :show, shallow: true do
    resources :goals, shallow: true do
      resources :milestones
      resources :posts, shallow: true do
        resources :comments
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :goal, inverse_of: :posts
  has_many :comments, inverse_of: :post, dependent: :destroy

  validates :title, :content, :goal, presence: true
  validates :title, length: { maximum: 80 }
  validates :content, length: { maximum: 800 } #should only be for FREE users

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource :goal
  load_and_authorize_resource :post, :through => :goal, :shallow => true
  before_filter :set_goal

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @posts = @posts.includes(:comments => :user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
  end

  def create
    if @post.save
      redirect_to goal_posts_path(@goal), notice: 'This post was successfully saved.'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_path(@post), notice: 'This post was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to goal_posts_path(@goal), notice: 'This post was deleted.'
  end

  def post_params
    params.require(:post).permit(:title, :content, :goal_id)
  end

  protected

  def set_goal
    @goal ||= @post.goal
  end

end

app/views/posts/_form.html.erb
<%= bootstrap_form_for @post.new_record? ? [@goal, @post] : [@post] do |f| %>

    <%= f.alert_message 'Please fix the errors below.' %>

    <div class="field">
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit 'Save' %>
    </div>

<% end %>

app/views/posts/_post.html.erb
<p>
  <%= display_full_date(post.created_at.to_date) %>
</p>

<p>
  <strong>Title:</strong>
  <%= post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= post.content %>
</p>

<% if can? :update, post %>
    <%= link_to 'Edit', edit_post_path(post) %>
<% end %>
<% if can? :destroy, post %>
    <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
<% end %>

<% if user_signed_in? %>
    <div>
      <%= render partial: "comments/form", locals: { post: post } %>
    </div>
<% end %>
<div id="comments-<%= post.id %>">
  <%= render partial: "comments/comment", collection: post.comments.reverse %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Progress Journal</h1>
<% if can? :create, Post.new(goal: @goal) %>
    <%= link_to 'Add Post', new_goal_post_path(@goal) %>
<% end %>

<% if @posts.blank? %>
    <h4>You do not currently have any posts</h4>
<% else %>
    <%= render @posts %>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render @post %>