config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, :only => :show, shallow: true do
    resources :goals, shallow: true do
      resources :milestones
      resources :posts, shallow: true do
        resources :comments
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search,
                  :against => { :title => 'A', :description => 'B' },
                  :using => { :tsearch => { :prefix => true } }
  has_many :milestones, inverse_of: :goal, dependent: :destroy
  has_many :goal_tags, inverse_of: :goal, dependent: :destroy
  has_many :tags, :through => :goal_tags
  has_many :posts, inverse_of: :goal, dependent: :destroy
  belongs_to :user, inverse_of: :goals
  belongs_to :group, inverse_of: :goals

  enum status: [ :active, :closed, :completed ] #DO NOT change this order
  enum visibility: [ :publiced, :privated ] #DO NOT change this order

  validates :title, :description, :status, :visibility, :user, presence: true
  validates :title, length: { maximum: 80 }, uniqueness: { scope: :user_id }
  validates :description, length: { maximum: 800 } #should only be for FREE users
  validate :maximum_active_goals_per_user, :maximum_goal_tags

  scope :viewable, -> { where visibility: 'publiced', group_id: nil }
  scope :personal_goals, -> { where group_id: nil }
  scope :group_goals, -> { where.not group_id: nil }

  def personal_goal?
    group_id.nil?
  end

  def group_goal?
    group_id.present?
  end

  private

  def maximum_active_goals_per_user
    if user.present? && status.present? && status == 'active'
      active_goals = Goal.where(user_id: user.id, status: Goal.statuses[:active])
      if active_goals.count == 3
        if new_record? || (!active_goals.map(&:id).include?(self.id))
          errors.add :base, 'You can only have three active goals at a time. Please complete or close an active goal before
                          starting a new one.'
        end
      end
    end
  end

  def maximum_goal_tags
    if self.goal_tags.count > 3
      errors.add :base, 'You can only add a maximum of 3 tags'
    end
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :goal, :through => :user, :shallow => true
  before_filter :set_user
  skip_authorize_resource :user, :only => :index

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :remove_blank_tags, :only => [:create]

  def index
    @goals = @goals.includes(:tags).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
  end

  def create
    if @goal.save
      redirect_to user_goals_path(@user), notice: 'This goal was successfully saved.'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @goal.update_attributes(goal_params)
      redirect_to user_goals_path(@user), notice: 'This goal was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @goal.destroy
    redirect_to user_goals_path(@user), notice: 'This goal was deleted.'
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :visibility, :status, :user_id, :tag_ids => [])
  end

  protected

  def set_user
    @user ||= @goal.user
  end

  def remove_blank_tags
    params[:goal][:tag_ids].reject!(&:blank?) if params[:goal][:tag_ids].present?
  end

end

app/views/goals/_form.html.erb
<%= bootstrap_form_for @goal.new_record? ? [@user, @goal] : [@goal] do |f| %>

    <%= f.alert_message 'Please fix the errors below.' %>

    <% unless @goal.new_record? %>
        <div class="field">
          <%= f.form_group :status, label: { text: 'Status' } do %>
              <%= f.radio_button :status, 'active', checked: @goal.active?, label: 'Active' %>
              <%= f.radio_button :status, 'closed', checked: @goal.closed?, label: 'Closed' %>
              <%= f.radio_button :status, 'completed', checked: @goal.completed?, label: 'Completed' %>
        <% end %>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.form_group :visibility, label: { text: 'Visibility' } do %>
          <%= f.radio_button :visibility, 'publiced', checked: true, label: 'Public' %>
          <%= f.radio_button :visibility, 'privated', label: 'Private' %>
      <% end %>
    </div>

    <div class="field">
      <% if action_name == 'edit' %>
        <%= f.select :tag_ids, options_from_collection_for_select(Tag.all, :id, :name, @goal.tags.map(&:id)), { :label => "Tags" }, id: 'tag-select', multiple: "multiple" %>
      <% else %>
        <%= f.select :tag_ids, options_from_collection_for_select(Tag.all, :id, :name, params[:goal] && params[:goal][:tag_ids] ? params[:goal][:tag_ids] : ""), { :label => "Tags" }, id: 'tag-select', multiple: "multiple" %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit 'Save' %>
    </div>

<% end %>

app/views/goals/_goal.html.erb
<p>
  <strong>Status:</strong>
  <%= goal.status.capitalize %>
</p>

<p>
  <strong>Title:</strong>
  <%= goal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= goal.description %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= display_visibility(goal.visibility) %>
</p>

<p>
  <strong>Tags:</strong>
  <%= display_tags(goal.tags) %>
</p>

<% if can? :update, goal %>
    <%= link_to 'Edit', edit_goal_path(goal) %>
<% end %>
<% if can? :destroy, goal %>
    <%= link_to 'Delete', goal_path(goal), method: :delete, data: { confirm: 'Are you sure you want to delete this goal?' } %>
<% end %>
<%= link_to 'Progress Journal',  goal_posts_path(goal) %>
<%= link_to 'Action Plan',  goal_milestones_path(goal) %>

app/views/goals/_goal_search.html.erb
<div><%= goal.user.username %></div>
<div><%= goal.title %></div>
<div><%= goal.description %></div>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render 'form' %>

app/views/goals/index.html.erb
<h1>Goals</h1>
<% if can? :create, Goal.new(user: @user) %>
    <%= link_to 'Add Goal', new_user_goal_path(@user) %>
<% end %>

<% if @goals.blank? %>
    <h4>You do not currently have any goals</h4>
<% else %>
    <%= render @goals %>
<% end %>

<%= paginate @goals %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

app/views/goals/show.html.erb
<%= render @goal %>